[workspace]
members = [
    "ec_2024",
    "ec_2025",
]

resolver = "3"

[workspace.dependencies]
anyhow = "1.0"
pathfinding = "4.14.0"
serde_json = "1.0.143"
rustc-hash = "2.1.1"
itertools = "0.14.0"
rayon = "1.11.0"

[profile.release]
debug = 2
